### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/wren#1]
The next steps are roughly:

- [x] Select programming language variant (if applicable)
- [x] Select testing framework
- [x] Select assertion framework #3
- [x] Write first exercise
- [x] First ~20 optional exercises #2
- [x] Add the track to the site as inactive
- [x] Request a track icon #7
- [x] Write "getting started" instructions for people using the track
- [x] Launch!
- [x] Prepare for open source contributions from strangers

---

Polish/cleanup:

- [x] Move `wren-testie` work back into main repo and add script to vendor it or use git subwhatever
- [x] Review all test docs to make sure nothing JS specific is there
- [x] `Expect.that ... toBe` doesn't read quite right
- [x] Finish writing overall track docs

---

Edit this issue to keep track of the tasks you're working on towards launch.

We have a rough guide for how to launch a track, which is sorely outdated but
quite possibly better than nothing (I'm so sorry, I'm waaaay behind on getting
documentation updated).
https://github.com/exercism/legacy-docs/blob/main/language-tracks/launch/README.md

Check out https://github.com/orgs/exercism/teams/track-maintainers/discussions/1
for details about the #maintaining-\<track\> channels and private #maintainers channel in the exercism-team Slack workspace.

Please ask if you have any questions or if anything is confusing!

**Comment by iHiD** [comment]
@joshgoebel You're in the game! :)

**Comment by iHiD** [comment]
@joshgoebel Maybe organise a 1-1 with @erikschierboom to get started

**Comment by joshgoebel** [comment]
I think we made it (since launch is tomorrow), so I'm closing this.
